// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeVKT239voLcfIwcxDOKZMOGKMUwSwoQg',
    appId: '1:961709455206:web:8b2ebb53bcb3767f653aa7',
    messagingSenderId: '961709455206',
    projectId: 'store-hub-creativa',
    authDomain: 'store-hub-creativa.firebaseapp.com',
    storageBucket: 'store-hub-creativa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCExn3Z7or63B_tqy444i9R0335eN9DAJ8',
    appId: '1:961709455206:android:14139992c42607a4653aa7',
    messagingSenderId: '961709455206',
    projectId: 'store-hub-creativa',
    storageBucket: 'store-hub-creativa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHL3NYCKq5hclW2JtABh78e_HAZOUnlTo',
    appId: '1:961709455206:ios:cbc3a88b983275f5653aa7',
    messagingSenderId: '961709455206',
    projectId: 'store-hub-creativa',
    storageBucket: 'store-hub-creativa.firebasestorage.app',
    iosBundleId: 'com.example.storeHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHL3NYCKq5hclW2JtABh78e_HAZOUnlTo',
    appId: '1:961709455206:ios:cbc3a88b983275f5653aa7',
    messagingSenderId: '961709455206',
    projectId: 'store-hub-creativa',
    storageBucket: 'store-hub-creativa.firebasestorage.app',
    iosBundleId: 'com.example.storeHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeVKT239voLcfIwcxDOKZMOGKMUwSwoQg',
    appId: '1:961709455206:web:9f56fdc169adf3ce653aa7',
    messagingSenderId: '961709455206',
    projectId: 'store-hub-creativa',
    authDomain: 'store-hub-creativa.firebaseapp.com',
    storageBucket: 'store-hub-creativa.firebasestorage.app',
  );
}
